spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#自定义路由访问地址
zuul:
  routes:
    myProduct:
      path: /myProduct/**
      serviceId: PRODUCT
      #zuul默认不传递Cookie、Set-Cookie、Authorization到接口方法里，这里设置可传递：设置sensitiveHeaders为空即可
      sensitiveHeaders:
 #全部服务都可传递Cookie、Set-Cookie、Authorization
 sensitive-headers: 
